apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-analytics-api
  namespace: attribution-platform
  labels:
    app: ml-analytics-api
    tier: ml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-analytics-api
  template:
    metadata:
      labels:
        app: ml-analytics-api
        tier: ml
    spec:
      containers:
      - name: ml-analytics
        image: unmogrowp/ml-analytics:latest
        ports:
        - containerPort: 8091
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: PORT
          value: "8091"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8091
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8091
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ml-analytics-api
  namespace: attribution-platform
spec:
  selector:
    app: ml-analytics-api
  ports:
  - port: 8091
    targetPort: 8091
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ml-analytics-hpa
  namespace: attribution-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ml-analytics-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
