apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: attribution-platform
data:
  ml-alerts.yml: |
    groups:
    - name: ml-services-alerts
      rules:
      # High Prediction Latency Alerts
      - alert: HighMLPredictionLatency
        expr: histogram_quantile(0.95, ml_prediction_latency_seconds_bucket) > 2
        for: 2m
        labels:
          severity: warning
          service: ml-analytics
        annotations:
          summary: "High ML prediction latency detected"
          description: "95th percentile prediction latency is {{ $value }}s for ML Analytics API"

      - alert: HighAttributionLatency
        expr: histogram_quantile(0.95, attribution_calculation_latency_seconds_bucket) > 1
        for: 2m
        labels:
          severity: warning
          service: attribution-ml
        annotations:
          summary: "High attribution calculation latency"
          description: "95th percentile attribution latency is {{ $value }}s"

      - alert: HighFraudDetectionLatency
        expr: histogram_quantile(0.95, fraud_detection_latency_seconds_bucket) > 0.5
        for: 2m
        labels:
          severity: critical
          service: fraud-detection
        annotations:
          summary: "High fraud detection latency"
          description: "95th percentile fraud detection latency is {{ $value }}s (critical for real-time fraud prevention)"

      # High Error Rate Alerts
      - alert: HighAPIErrorRate
        expr: |
          (
            rate(api_requests_total{code=~"5.."}[5m]) /
            rate(api_requests_total[5m])
          ) * 100 > 5
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: "High API error rate detected"
          description: "Error rate is {{ $value }}% for {{ $labels.service }}"

      # Service Availability Alerts
      - alert: MLServiceDown
        expr: up{job=~"ml-analytics|attribution-ml|fraud-detection|ltv-prediction"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "ML Service is down"
          description: "{{ $labels.job }} service is not responding"

      # High Fraud Detection Rate (could indicate attack)
      - alert: HighFraudDetectionRate
        expr: rate(fraud_detections_total{result="high"}[10m]) > 10
        for: 5m
        labels:
          severity: warning
          service: fraud-detection
        annotations:
          summary: "High fraud detection rate"
          description: "Fraud detection rate is {{ $value }}/minute - possible attack in progress"

      # Low Prediction Volume (could indicate system issues)
      - alert: LowPredictionVolume
        expr: rate(ml_predictions_total[10m]) < 1
        for: 10m
        labels:
          severity: warning
          service: ml-analytics
        annotations:
          summary: "Low ML prediction volume"
          description: "ML prediction rate is {{ $value }}/minute - unusually low"

      # Memory and CPU Alerts
      - alert: HighMemoryUsage
        expr: |
          (
            container_memory_working_set_bytes{pod=~".*ml.*|.*attribution.*|.*fraud.*|.*ltv.*"} /
            container_spec_memory_limit_bytes
          ) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage in ML service"
          description: "Memory usage is {{ $value }}% for {{ $labels.pod }}"

      - alert: HighCPUUsage
        expr: |
          (
            rate(container_cpu_usage_seconds_total{pod=~".*ml.*|.*attribution.*|.*fraud.*|.*ltv.*"}[5m]) /
            container_spec_cpu_quota * container_spec_cpu_period
          ) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage in ML service"
          description: "CPU usage is {{ $value }}% for {{ $labels.pod }}"

    - name: business-metrics-alerts
      rules:
      # Business Logic Alerts
      - alert: UnusualLTVPredictions
        expr: avg_over_time(ltv_predictions_total[1h]) > avg_over_time(ltv_predictions_total[24h]) * 3
        for: 15m
        labels:
          severity: info
          category: business
        annotations:
          summary: "Unusual LTV prediction volume"
          description: "LTV prediction volume is 3x higher than 24h average"

      - alert: HighAttributionVariance
        expr: stddev_over_time(attribution_calculations_total[1h]) > 100
        for: 30m
        labels:
          severity: info
          category: business
        annotations:
          summary: "High variance in attribution calculations"
          description: "Attribution calculation volume shows high variance"