# UnMoGrowP Prometheus Configuration
# Production-ready metrics collection for attribution platform

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'unmogrowp-local'
    environment: 'development'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093  # Add when AlertManager is configured

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # API Server (Bun + Hono)
  - job_name: 'unmogrowp-api'
    static_configs:
      - targets: ['host.docker.internal:3004']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Backend Go Service
  - job_name: 'unmogrowp-backend'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # ClickHouse metrics
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['host.docker.internal:8123']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL metrics (via postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:9187']
    scrape_interval: 30s
    # Note: Requires postgres_exporter to be running

  # Redis metrics (via redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:9121']
    scrape_interval: 30s
    # Note: Requires redis_exporter to be running

  # Kafka metrics (via kafka_exporter)
  - job_name: 'kafka'
    static_configs:
      - targets: ['host.docker.internal:9308']
    scrape_interval: 30s
    # Note: Requires kafka_exporter to be running

# Recording rules for performance optimization
recording_rules:
  - name: unmogrowp_aggregation_rules
    rules:
      # API Request rate (per minute)
      - record: unmogrowp:api_requests_per_minute
        expr: rate(http_requests_total[1m]) * 60

      # API Error rate
      - record: unmogrowp:api_error_rate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m])

      # Event ingestion rate
      - record: unmogrowp:events_per_second
        expr: rate(events_processed_total[1m])

      # Database connection pool usage
      - record: unmogrowp:db_connections_usage
        expr: db_connections_active / db_connections_max

# Alerting rules for production monitoring
alerting_rules:
  - name: unmogrowp_alerts
    rules:
      # High API error rate
      - alert: HighAPIErrorRate
        expr: unmogrowp:api_error_rate > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High API error rate detected"
          description: "API error rate is {{ $value }}% over the last 5 minutes"

      # High latency
      - alert: HighAPILatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High API latency detected"
          description: "95th percentile latency is {{ $value }}s"

      # Service down
      - alert: ServiceDown
        expr: up == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service has been down for more than 2 minutes"

      # High memory usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 90%"

      # High CPU usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 85% for more than 5 minutes"

      # Low disk space
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"}) < 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space"
          description: "Less than 10% disk space remaining"