# ============================================================================
# Load Testing Environment for UnMoGrowP Attribution Platform
# K6 + InfluxDB + Grafana for comprehensive performance testing
# ============================================================================

version: '3.8'

networks:
  load-test:
    driver: bridge

services:
  # =========================================================================
  # K6 Load Testing Engine
  # =========================================================================
  k6:
    image: grafana/k6:0.47.0
    container_name: k6-load-test
    networks:
      - load-test
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
      - BASE_URL=http://host.docker.internal:8080
      - API_KEY=test-load-key-123456789
    volumes:
      - ./k6-load-test.js:/scripts/load-test.js
      - ./results:/results
    command: run /scripts/load-test.js
    depends_on:
      - influxdb
    profiles:
      - load-test

  # =========================================================================
  # InfluxDB - Time Series Database for Metrics
  # =========================================================================
  influxdb:
    image: influxdb:2.7
    container_name: influxdb-load-test
    networks:
      - load-test
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-loadtest_env_required}
      - DOCKER_INFLUXDB_INIT_ORG=unmogrowp
      - DOCKER_INFLUXDB_INIT_BUCKET=k6
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN:-loadtest_token_env_required}
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # =========================================================================
  # Grafana - Load Test Metrics Dashboard
  # =========================================================================
  grafana-load-test:
    image: grafana/grafana:10.2.0
    container_name: grafana-load-test
    networks:
      - load-test
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-loadtest_grafana_env_required}
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_load_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - influxdb
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # =========================================================================
  # Load Test Orchestrator (Custom)
  # =========================================================================
  load-orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    container_name: load-orchestrator
    networks:
      - load-test
    environment:
      - PLATFORM_URL=http://host.docker.internal:8080
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=${INFLUXDB_ADMIN_TOKEN:-loadtest_token_env_required}
      - TEST_DURATION=1800  # 30 minutes
      - TARGET_RPS=1000000  # 1M requests per second
    volumes:
      - ./results:/results
      - ./scripts:/scripts
    depends_on:
      - influxdb
      - grafana-load-test
    profiles:
      - orchestrator

  # =========================================================================
  # Performance Monitor (Resource Usage)
  # =========================================================================
  performance-monitor:
    image: prom/node-exporter:v1.6.1
    container_name: performance-monitor
    networks:
      - load-test
    ports:
      - "9100:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    profiles:
      - monitoring

volumes:
  influxdb_data:
  influxdb_config:
  grafana_load_data:

# ============================================================================
# Usage Instructions:
#
# 1. Start load testing infrastructure:
#    docker-compose -f docker-compose.load-test.yml up -d
#
# 2. Run basic load test:
#    docker-compose -f docker-compose.load-test.yml --profile load-test up k6
#
# 3. Run with orchestrator (advanced scenarios):
#    docker-compose -f docker-compose.load-test.yml --profile orchestrator up
#
# 4. Enable system monitoring:
#    docker-compose -f docker-compose.load-test.yml --profile monitoring up -d
#
# 5. View results:
#    - Grafana: http://localhost:3001 (admin/${GRAFANA_PASSWORD})
#    - InfluxDB: http://localhost:8086 (admin/${INFLUXDB_PASSWORD})
#
# ============================================================================