global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'attribution-platform-local'
    environment: 'development'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ML Services (adjust IPs/ports for your local setup)
  - job_name: 'ml-analytics'
    static_configs:
      - targets: ['host.docker.internal:8091']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'attribution-ml'
    static_configs:
      - targets: ['host.docker.internal:8086']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'fraud-detection'
    static_configs:
      - targets: ['host.docker.internal:8087']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'ltv-prediction'
    static_configs:
      - targets: ['host.docker.internal:8088']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # System monitoring
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Monitoring stack self-monitoring
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']