name: AI Daily Repository Monitor
on:
  schedule:
    - cron: "0 8 * * *"   # Каждый день в 11:00 по Киеву (08:00 UTC)
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode'
        required: false
        default: 'false'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  daily-monitor:
    runs-on: ubuntu-latest
    name: Run AI Daily Analysis
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run AI analysis
        env:
          GITHUB_TOKEN: ${{ secrets.UNMOGROWP_MONITOR_TOKEN }}
          REPO_URL: "https://github.com/kik200771-oss/UnMoGrowP"
        run: |
          python3 scripts/ai_monitor.py