name: Daily Repository Monitor
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - name: Run monitor
        env:
          GITHUB_TOKEN: ${{ secrets.UNMOGROWP_MONITOR_TOKEN }}
          REPO_URL: "https://github.com/kik200771-oss/UnMoGrowP"
        run: python3 scripts/ai_monitor.py