name: Simple Test 2

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Test step
        run: echo "Hello from Simple Test 2"